const Nationalities =[
    { "label": "Afghan", "value": "AF" },
    { "label": "Albanian", "value": "AL" },
    { "label": "Algerian", "value": "DZ" },
    { "label": "American", "value": "US" },
    { "label": "Andorran", "value": "AD" },
    { "label": "Angolan", "value": "AO" },
    { "label": "Antiguan", "value": "AG" },
    { "label": "Argentine", "value": "AR" },
    { "label": "Armenian", "value": "AM" },
    { "label": "Australian", "value": "AU" },
    { "label": "Austrian", "value": "AT" },
    { "label": "Azerbaijani", "value": "AZ" },
    { "label": "Bahamian", "value": "BS" },
    { "label": "Bahraini", "value": "BH" },
    { "label": "Bangladeshi", "value": "BD" },
    { "label": "Barbadian", "value": "BB" },
    { "label": "Belarusian", "value": "BY" },
    { "label": "Belgian", "value": "BE" },
    { "label": "Belizean", "value": "BZ" },
    { "label": "Beninese", "value": "BJ" },
    { "label": "Bhutanese", "value": "BT" },
    { "label": "Bolivian", "value": "BO" },
    { "label": "Bosnian", "value": "BA" },
    { "label": "Botswanan", "value": "BW" },
    { "label": "Brazilian", "value": "BR" },
    { "label": "British", "value": "GB" },
    { "label": "Bruneian", "value": "BN" },
    { "label": "Bulgarian", "value": "BG" },
    { "label": "Burkinabe", "value": "BF" },
    { "label": "Burmese", "value": "MM" },
    { "label": "Burundian", "value": "BI" },
    { "label": "Cambodian", "value": "KH" },
    { "label": "Cameroonian", "value": "CM" },
    { "label": "Canadian", "value": "CA" },
    { "label": "Cape Verdean", "value": "CV" },
    { "label": "Central African", "value": "CF" },
    { "label": "Chadian", "value": "TD" },
    { "label": "Chilean", "value": "CL" },
    { "label": "Chinese", "value": "CN" },
    { "label": "Colombian", "value": "CO" },
    { "label": "Comoran", "value": "KM" },
    { "label": "Congolese (Congo-Brazzaville)", "value": "CG" },
    { "label": "Congolese (Congo-Kinshasa)", "value": "CD" },
    { "label": "Costa Rican", "value": "CR" },
    { "label": "Croatian", "value": "HR" },
    { "label": "Cuban", "value": "CU" },
    { "label": "Cypriot", "value": "CY" },
    { "label": "Czech", "value": "CZ" },
    { "label": "Danish", "value": "DK" },
    { "label": "Djiboutian", "value": "DJ" },
    { "label": "Dominican", "value": "DO" },
    { "label": "Dutch", "value": "NL" },
    { "label": "East Timorese", "value": "TL" },
    { "label": "Ecuadorean", "value": "EC" },
    { "label": "Egyptian", "value": "EG" },
    { "label": "Emirati", "value": "AE" },
    { "label": "Equatorial Guinean", "value": "GQ" },
    { "label": "Eritrean", "value": "ER" },
    { "label": "Estonian", "value": "EE" },
    { "label": "Ethiopian", "value": "ET" },
    { "label": "Fijian", "value": "FJ" },
    { "label": "Filipino", "value": "PH" },
    { "label": "Finnish", "value": "FI" },
    { "label": "French", "value": "FR" },
    { "label": "Gabonese", "value": "GA" },
    { "label": "Gambian", "value": "GM" },
    { "label": "Georgian", "value": "GE" },
    { "label": "German", "value": "DE" },
    { "label": "Ghanaian", "value": "GH" },
    { "label": "Greek", "value": "GR" },
    { "label": "Grenadian", "value": "GD" },
    { "label": "Guatemalan", "value": "GT" },
    { "label": "Guinean", "value": "GN" },
    { "label": "Guinean-Bissauan", "value": "GW" },
    { "label": "Guyanese", "value": "GY" },
    { "label": "Haitian", "value": "HT" },
    { "label": "Honduran", "value": "HN" },
    { "label": "Hungarian", "value": "HU" },
    { "label": "Icelander", "value": "IS" },
    { "label": "Indian", "value": "IN" },
    { "label": "Indonesian", "value": "ID" },
    { "label": "Iranian", "value": "IR" },
    { "label": "Iraqi", "value": "IQ" },
    { "label": "Irish", "value": "IE" },
    { "label": "Israeli", "value": "IL" },
    { "label": "Italian", "value": "IT" },
    { "label": "Ivorian", "value": "CI" },
    { "label": "Jamaican", "value": "JM" },
    { "label": "Japanese", "value": "JP" },
    { "label": "Jordanian", "value": "JO" },
    { "label": "Kazakh", "value": "KZ" },
    { "label": "Kenyan", "value": "KE" },
    { "label": "Kittitian", "value": "KN" },
    { "label": "Kuwaiti", "value": "KW" },
    { "label": "Kyrgyzstani", "value": "KG" },
    { "label": "Lao", "value": "LA" },
    { "label": "Latvian", "value": "LV" },
    { "label": "Lebanese", "value": "LB" },
    { "label": "Liberian", "value": "LR" },
    { "label": "Libyan", "value": "LY" },
    { "label": "Liechtensteiner", "value": "LI" },
    { "label": "Lithuanian", "value": "LT" },
    { "label": "Luxembourger", "value": "LU" },
    { "label": "Macedonian", "value": "MK" },
    { "label": "Malagasy", "value": "MG" },
    { "label": "Malawian", "value": "MW" },
    { "label": "Malaysian", "value": "MY" },
    { "label": "Maldivian", "value": "MV" },
    { "label": "Malian", "value": "ML" },
    { "label": "Maltese", "value": "MT" },
    { "label": "Marshallese", "value": "MH" },
    { "label": "Mauritanian", "value": "MR" },
    { "label": "Mauritian", "value": "MU" },
    { "label": "Mexican", "value": "MX" },
    { "label": "Micronesian", "value": "FM" },
    { "label": "Moldovan", "value": "MD" },
    { "label": "Monacan", "value": "MC" },
    { "label": "Mongolian", "value": "MN" },
    { "label": "Montenegrin", "value": "ME" },
    { "label": "Moroccan", "value": "MA" },
    { "label": "Mozambican", "value": "MZ" },
    { "label": "Namibian", "value": "NA" },
    { "label": "Nauruan", "value": "NR" },
    { "label": "Nepalese", "value": "NP" },
    { "label": "New Zealander", "value": "NZ" },
    { "label": "Nicaraguan", "value": "NI" },
    { "label": "Nigerien", "value": "NE" },
    { "label": "Nigerian", "value": "NG" },
    { "label": "North Korean", "value": "KP" },
    { "label": "Norwegian", "value": "NO" },
    { "label": "Omani", "value": "OM" },
    { "label": "Pakistani", "value": "PK" },
    { "label": "Palauan", "value": "PW" },
    { "label": "Palestinian", "value": "PS" },
    { "label": "Panamanian", "value": "PA" },
    { "label": "Papua New Guinean", "value": "PG" },
    { "label": "Paraguayan", "value": "PY" },
    { "label": "Peruvian", "value": "PE" },
    { "label": "Polish", "value": "PL" },
    { "label": "Portuguese", "value": "PT" },
    { "label": "Qatari", "value": "QA" },
    { "label": "Romanian", "value": "RO" },
    { "label": "Russian", "value": "RU" },
    { "label": "Rwandan", "value": "RW" },
    { "label": "Saint Lucian", "value": "LC" },
    { "label": "Samoan", "value": "WS" },
    { "label": "San Marinese", "value": "SM" },
    { "label": "Saudi Arabian", "value": "SA" },
    { "label": "Senegalese", "value": "SN" },
    { "label": "Serbian", "value": "RS" },
    { "label": "Seychellois", "value": "SC" },
    { "label": "Singaporean", "value": "SG" },
    { "label": "Slovak", "value": "SK" },
    { "label": "Slovenian", "value": "SI" },
    { "label": "Solomon Islander", "value": "SB" },
    { "label": "Somali", "value": "SO" },
    { "label": "South African", "value": "ZA" },
    { "label": "South Korean", "value": "KR" },
    { "label": "Spanish", "value": "ES" },
    { "label": "Sri Lankan", "value": "LK" },
    { "label": "Sudanese", "value": "SD" },
    { "label": "Surinamer", "value": "SR" },
    { "label": "Swazi", "value": "SZ" },
    { "label": "Swedish", "value": "SE" },
    { "label": "Swiss", "value": "CH" },
    { "label": "Syrian", "value": "SY" },
    { "label": "Taiwanese", "value": "TW" },
    { "label": "Tajikistani", "value": "TJ" },
    { "label": "Tanzanian", "value": "TZ" },
    { "label": "Thai", "value": "TH" },
    { "label": "Togolese", "value": "TG" },
    { "label": "Tongan", "value": "TO" },
    { "label": "Trinidadian", "value": "TT" },
    { "label": "Tunisian", "value": "TN" },
    { "label": "Turkish", "value": "TR" },
    { "label": "Turkmenistani", "value": "TM" },
    { "label": "Tuvaluan", "value": "TV" },
    { "label": "Ugandan", "value": "UG" },
    { "label": "Ukrainian", "value": "UA" },
    { "label": "Uruguayan", "value": "UY" },
    { "label": "Uzbekistani", "value": "UZ" },
    { "label": "Vanuatuan", "value": "VU" },
    { "label": "Venezuelan", "value": "VE" },
    { "label": "Vietnamese", "value": "VN" },
    { "label": "Yemeni", "value": "YE" },
    { "label": "Zambian", "value": "ZM" },
    { "label": "Zimbabwean", "value": "ZW" }
  ]
  
  export default Nationalities;